### ISSUE TITLE
Emoji picker of callout cards has a light background in dark mode

### ISSUE THREAD

**Issue by asenseofpradhyu** [TryGhost/Koenig#1083]
**Issue Summary**
As the title says, the emoji picker of callout cards has a light background in dark mode.

![editor_issue](https://github.com/TryGhost/Koenig/assets/24241624/0be53a73-f4cc-4e2f-a0b0-28116425b000)

**Steps to Reproduce**
Create a callout card in dark mode
Select the emoji picker
See that the emoji picker has a light background

This issue is direct reference from Ghost repo:- https://github.com/TryGhost/Ghost/issues/19038

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Koenig/pull/1126
