### ISSUE TITLE
Grammarly Extension doesn't seem to work with the main editor

### ISSUE THREAD

**Issue by Timothep** [TryGhost/Koenig#130]
The Grammarly extension is correctly enabled for the title box, but not for the main box.

![image](https://user-images.githubusercontent.com/594373/92707344-7f326400-f355-11ea-8770-b569e5e21b59.png)

I tried the steps [described here](https://support.grammarly.com/hc/en-us/articles/115000090392-I-do-not-see-the-G-icon-on-a-certain-web-page-or-in-a-certain-text-field-but-see-it-on-other-web-pages-) and everything seems to be OK.

Testing in MS Edge, Version 85.0.564.44 & Windows 10

**Comment by kevinansfield** [comment]
This is intentional, grammarly is explicitly disabled as it does not support the editor and will lock up the CPU in certain cases.

**Comment by Timothep** [comment]
Hi @kevinansfield, I see, thanks for the answer. That's a bummer. Is there any way this could be toggled?

**Comment by jamescauwelier** [comment]
I have the same question @kevinansfield. ProWritingAid is another grammar checker that seems to be disabled. I'd like to know more about the issue as I may be able to help. Even if it uses extensive resources, it should be up to the end-user to decide on this depending on the resources available on their machine and their use-case. I am not a professional writer and writing without a tool such as grammarly makes zero sense to me.
