### ISSUE TITLE
When copying from rendered post to editor, extra < strong > < strong > is being added

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Koenig#336]
### Issue Summary
- Extra < strong > < strong > is being added when when copying from rendered post to editor
- https://ghost.slack.com/archives/C025584CA/p1652285609044959

### To Reproduce
1. Copy < strong > code from rendered post
2. Paste code, extra < strong > < strong > are added
3. Same issue occurs here: http://bustle.github.io/mobiledoc-kit/demo/

### Technical details:

* Ghost Version: Ghost v4.47.1
* Node Version: N/A
* Browser/OS: Reproduced on Chrome v101.0.4951.64/macOS 12.3.1

### Screenshots:
<img width="1865" alt="screen_shot_2565-05-11_at_12 12 52" src="https://user-images.githubusercontent.com/91746772/167916490-568609aa-d5fc-4c0c-934e-a6dbbb1440af.png">
<img width="1929" alt="screen_shot_2565-05-11_at_12 14 08" src="https://user-images.githubusercontent.com/91746772/167916495-17dfa98e-51f7-4ca3-84a3-61ecd43750b8.png">

**Comment by Narcos101** [comment]
Hey @ErisDS can i contribute on this issue?
