### ISSUE TITLE
Overview on all packages?

### ISSUE THREAD

**Issue by JohnRSim** [TryGhost/Koenig#340]
I noticed there was a react package 
[koenig-react](https://github.com/TryGhost/Koenig/tree/main/packages/koenig-react)

But couldn't find any info on it.. 
Or the other packages any docs or release notes.

I installed it and tried it out -
![image](https://user-images.githubusercontent.com/364208/189538389-3f661947-8f0f-4e24-adf9-2eb11e5bfc1c.png)

Still a few issues but initially worked..
Now contemplating to use it or write from the ground up using https://github.com/bustle/mobiledoc-kit and svelte..
or to wait for more info and build upon it with the react package..

**Comment by kevinansfield** [comment]
That package was the very very early stages of an experiment to see if it might be possible to re-write our editor in React and wasn't complete or meant for re-use in any way. We've decided to follow a different path with a re-write based around a different editor framework so the `koenig-react` package no longer exists.

What is it you're attempting to do? Most everything in this repo is currently very specific to Ghost and isn't really set up for use outside of Ghost.

**Comment by JohnRSim** [comment]
Thanks @kevinansfield for the update. 👍 
I was just looking for a simplified editor and liked the experience of Koenig to write notes up for a demo app.

I'll go down the route of mobiledoc-kit with svelte and create a light weight version 
- using Koenig as inspiration for the UI.

Will keep my eyes out and watch the progress :)
