### ISSUE TITLE
Linked image in markdown malfunctioning (src attribute is wrong) 

### ISSUE THREAD

**Issue by benaltair** [TryGhost/Koenig#71]
When nesting a link (`<a>` tag) around an image in the Koenig markdown module, the `src` attribute in the generated HTML results in a 404 error. The URL is consistently incorrect.

### Steps to reproduce:
1. On a page or a post in the Koenig editor, add a markdown module with the "+" button.
2. Add an image, for example with the upload button. Code such as this will appear:
`![Amber-Opening-HD_1295-1](https://amberimageworks.org/content/images/2020/05/Amber-Opening-HD_1295-1.gif)`
3. Wrap this code with the structure for a link, making the code look like this:
`[![Amber-Opening-HD_1295-1](https://amberimageworks.org/content/images/2020/05/Amber-Opening-HD_1295-1.gif)](https://amberimageworks.org/culture/)`
This could be done with the link button or manually.

_Steps 2 and 3 can be done in any order._

### The Issue:
The image doesn't show up (at least on my installation).
![Annotation 2020-05-13 194827](https://user-images.githubusercontent.com/17771229/81886931-d153ac00-9552-11ea-8449-86850fbc973a.jpg)

There is a GET error caused by a 404, which seems to be because the link is showing up weird. This is the rendered code:
```
<a href="https://amberimageworks.org/culture/" class="image-link">
<img src="https://amberimageworks.org/content/images/2020/05/Annotation-2020-04-18!%5BAmber-Opening-HD_1295-1%5D(/content/images/2020/05/Amber-Opening-HD_1295-1.gif)mber-Opening-HD_1295-1.gif" alt="Annotation-2020-04-18-210918">
</a>
```
It seems that something weird is happening within the URL. It's worth noting that the markdown above is what's automatically generated using the upload/link tools in the built-in MD editor. If we adjust the image link in the MD editor to relative rather than the automatic absolute value, the nested MD syntax renders correctly. For example:
`[![Annotation-2020-04-18-210918](/content/images/2020/05/Annotation-2020-04-18-210918.jpg)](https://amberimageworks.org/culture/)`
will render as:
```
<a href="https://amberimageworks.org/culture/" class="image-link"><img src="https://amberimageworks.org/content/images/2020/05/Annotation-2020-04-18-210918.jpg" alt="Annotation-2020-04-18-210918" class="no-lightense"></a>
```
The image displays correctly when using a relative link in the MD editor.

### Idea
Perhaps the solution could be as simple as changing the generated code to relative instead of absolute when uploading an image. That wouldn't necessarily address the underlying issue that seems to be present, which is generating illogical code that consistently results in 404 errors.

If I can provide any more information, I'm happy to help.

**Comment by benaltair** [comment]
This may have something to do with certain characters in the URL? I'm not sure. I found the issue showing up differently in this case:
`[![Occasional-Songs-We-Are-With-You-Now---Forever](https://amberimageworks.org/content/images/2020/05/Occasional-Songs-We-Are-With-You-Now---Forever.jpg)](https://amberimageworks.org/culture/we-are-with-you/)`

This renders as:
```
<a href="https://amberimageworks.org/links/!%5BOccasional-Songs-We-Are-With-You-Now---Forever%5D(/content/images/2020/05/Occasional-Songs-We-Are-With-You-Now---Forever.jpg)With-You-Now---Forever.jpg" class="image-link"><img src="https://amberimageworks.org/content/images/2020/05/Occasional-Songs-We-Are-With-You-Now---Forever.jpg" alt="Occasional-Songs-We-Are-With-You-Now---Forever" class="no-lightense"></a>
```
![Annotation 2020-05-13 202137](https://user-images.githubusercontent.com/17771229/81888990-5e98ff80-9557-11ea-804b-4f5954ee7434.jpg)

Notice the plain text showing up outside the `<a>` tag for some reason.

**Comment by kevinansfield** [comment]
@benaltair I'm not able to reproduce any of these cases using latest version of Ghost. If you're on an earlier version can you please try upgrading? If you still see problems, please open an issue on https://github.com/tryghost/ghost, thanks 🙂
